{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.sample.PopupKit\/documentation\/PopupKit\/Popup"},"metadata":{"externalID":"c:@M@PopupKit@objc(cs)Popup","symbolKind":"class","navigatorTitle":[{"text":"Popup","kind":"identifier"}],"role":"symbol","modules":[{"name":"PopupKit"}],"title":"Popup","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Popup","kind":"identifier"}],"roleHeading":"Class"},"topicSections":[{"identifiers":["doc:\/\/com.sample.PopupKit\/documentation\/PopupKit\/Popup\/init(with:message:dismissTitle:dismissTapped:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.sample.PopupKit\/documentation\/PopupKit\/Popup\/setButtonBackground(color:)"],"title":"Instance Methods"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.sample.PopupKit\/objc(cs)UIView"]},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.sample.PopupKit\/objc(pl)NSCoding","doc:\/\/com.sample.PopupKit\/objc(pl)NSObject","doc:\/\/com.sample.PopupKit\/objc(pl)CALayerDelegate","doc:\/\/com.sample.PopupKit\/s7CVarArgP","doc:\/\/com.sample.PopupKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.sample.PopupKit\/s23CustomStringConvertibleP","doc:\/\/com.sample.PopupKit\/SQ","doc:\/\/com.sample.PopupKit\/SH","doc:\/\/com.sample.PopupKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.sample.PopupKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.sample.PopupKit\/objc(pl)UIAppearance","doc:\/\/com.sample.PopupKit\/objc(pl)UIAppearanceContainer","doc:\/\/com.sample.PopupKit\/objc(pl)UICoordinateSpace","doc:\/\/com.sample.PopupKit\/objc(pl)UIDynamicItem","doc:\/\/com.sample.PopupKit\/objc(pl)UIFocusEnvironment","doc:\/\/com.sample.PopupKit\/objc(pl)UIFocusItem","doc:\/\/com.sample.PopupKit\/objc(pl)UIFocusItemContainer","doc:\/\/com.sample.PopupKit\/objc(pl)UILargeContentViewerItem","doc:\/\/com.sample.PopupKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.sample.PopupKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.sample.PopupKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.sample.PopupKit\/5UIKit23UITraitChangeObservableP","doc:\/\/com.sample.PopupKit\/objc(pl)UITraitEnvironment","doc:\/\/com.sample.PopupKit\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo"}],"variants":[{"paths":["\/documentation\/popupkit\/popup"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/popupkit\/popup"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.sample.PopupKit\/documentation\/PopupKit"]]},"seeAlsoSections":[{"title":"Files","identifiers":["doc:\/\/com.sample.PopupKit\/documentation\/PopupKit\/PopupView"],"generated":true}],"abstract":[{"type":"text","text":"Popup View class used to show alert type view"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Popup"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Overview","anchor":"overview","level":2,"type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This class is used to show alert type of view to highlight some info"}]}]}],"type":"unorderedList"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","references":{"doc://com.sample.PopupKit/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.sample.PopupKit\/objc(pl)UIAccessibilityIdentification","type":"unresolvable"},"doc://com.sample.PopupKit/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.sample.PopupKit\/objc(pl)UIFocusEnvironment","type":"unresolvable"},"doc://com.sample.PopupKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sample.PopupKit\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.sample.PopupKit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.sample.PopupKit\/s7CVarArgP","type":"unresolvable"},"doc://com.sample.PopupKit/documentation/PopupKit":{"type":"topic","title":"PopupKit","kind":"symbol","url":"\/documentation\/popupkit","identifier":"doc:\/\/com.sample.PopupKit\/documentation\/PopupKit","abstract":[{"text":"Popup class conforms to UIView, It is used to show alert kind of view to highlight some info","type":"text"}],"role":"collection"},"doc://com.sample.PopupKit/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/com.sample.PopupKit\/objc(pl)NSCoding","type":"unresolvable"},"doc://com.sample.PopupKit/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.sample.PopupKit\/objc(pl)UIDynamicItem","type":"unresolvable"},"doc://com.sample.PopupKit/documentation/PopupKit/Popup/setButtonBackground(color:)":{"url":"\/documentation\/popupkit\/popup\/setbuttonbackground(color:)","role":"symbol","kind":"symbol","title":"setButtonBackground(color:)","abstract":[{"text":"Set Dismiss button background color","type":"text"}],"identifier":"doc:\/\/com.sample.PopupKit\/documentation\/PopupKit\/Popup\/setButtonBackground(color:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setButtonBackground"},{"kind":"text","text":"("},{"text":"color","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic"},"doc://com.sample.PopupKit/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/com.sample.PopupKit\/5UIKit23UITraitChangeObservableP"},"doc://com.sample.PopupKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","type":"unresolvable","identifier":"doc:\/\/com.sample.PopupKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.sample.PopupKit/documentation/PopupKit/PopupView":{"navigatorTitle":[{"kind":"identifier","text":"PopupView"}],"type":"topic","identifier":"doc:\/\/com.sample.PopupKit\/documentation\/PopupKit\/PopupView","url":"\/documentation\/popupkit\/popupview","role":"symbol","abstract":[{"text":"A SwiftUI view representable for ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.sample.PopupKit\/documentation\/PopupKit\/Popup","type":"reference"},{"text":" class","type":"text"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PopupView"}],"title":"PopupView"},"doc://com.sample.PopupKit/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/com.sample.PopupKit\/objc(pl)UIResponderStandardEditActions"},"doc://com.sample.PopupKit/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/com.sample.PopupKit\/objc(pl)UIUserActivityRestoring"},"doc://com.sample.PopupKit/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable","identifier":"doc:\/\/com.sample.PopupKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.sample.PopupKit/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","type":"unresolvable","identifier":"doc:\/\/com.sample.PopupKit\/objc(pl)CALayerDelegate"},"doc://com.sample.PopupKit/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/com.sample.PopupKit\/objc(pl)UIAppearanceContainer"},"doc://com.sample.PopupKit/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","type":"unresolvable","identifier":"doc:\/\/com.sample.PopupKit\/objc(pl)UIFocusItem"},"doc://com.sample.PopupKit/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable","identifier":"doc:\/\/com.sample.PopupKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.sample.PopupKit/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","type":"unresolvable","identifier":"doc:\/\/com.sample.PopupKit\/objc(pl)UILargeContentViewerItem"},"doc://com.sample.PopupKit/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","type":"unresolvable","identifier":"doc:\/\/com.sample.PopupKit\/objc(pl)UIFocusItemContainer"},"doc://com.sample.PopupKit/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/com.sample.PopupKit\/objc(pl)UITraitEnvironment"},"doc://com.sample.PopupKit/documentation/PopupKit/Popup":{"identifier":"doc:\/\/com.sample.PopupKit\/documentation\/PopupKit\/Popup","role":"symbol","url":"\/documentation\/popupkit\/popup","type":"topic","kind":"symbol","title":"Popup","abstract":[{"text":"Popup View class used to show alert type view","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Popup"}],"navigatorTitle":[{"kind":"identifier","text":"Popup"}]},"doc://com.sample.PopupKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.sample.PopupKit\/s28CustomDebugStringConvertibleP"},"doc://com.sample.PopupKit/objc(cs)UIView":{"title":"UIView","type":"unresolvable","identifier":"doc:\/\/com.sample.PopupKit\/objc(cs)UIView"},"doc://com.sample.PopupKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.sample.PopupKit\/objc(pl)NSObject"},"doc://com.sample.PopupKit/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","type":"unresolvable","identifier":"doc:\/\/com.sample.PopupKit\/objc(pl)UICoordinateSpace"},"doc://com.sample.PopupKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.sample.PopupKit\/SH"},"doc://com.sample.PopupKit/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","type":"unresolvable","identifier":"doc:\/\/com.sample.PopupKit\/objc(pl)UIAppearance"},"doc://com.sample.PopupKit/documentation/PopupKit/Popup/init(with:message:dismissTitle:dismissTapped:)":{"role":"symbol","abstract":[{"text":"Popup init method","type":"text"}],"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"dismissTitle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"dismissTapped","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"type":"topic","title":"init(with:message:dismissTitle:dismissTapped:)","url":"\/documentation\/popupkit\/popup\/init(with:message:dismisstitle:dismisstapped:)","identifier":"doc:\/\/com.sample.PopupKit\/documentation\/PopupKit\/Popup\/init(with:message:dismissTitle:dismissTapped:)"},"doc://com.sample.PopupKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.sample.PopupKit\/SQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"Popup","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Popup"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Popup"}]},{"value":null,"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.sample.PopupKit\/objc(cs)UIView"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Popup"},{"text":" : ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"]}]}},{"op":"replace","value":"Popup","path":"\/references\/doc:~1~1com.sample.PopupKit~1documentation~1PopupKit~1Popup\/title"},{"op":"replace","value":[{"text":"Popup","kind":"identifier"}],"path":"\/references\/doc:~1~1com.sample.PopupKit~1documentation~1PopupKit~1Popup\/fragments"}]}]}