{"sections":[],"metadata":{"title":"PopupKit","role":"collection","modules":[{"name":"PopupKit"}],"symbolKind":"module","roleHeading":"Framework","externalID":"PopupKit"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Popup class conforms to UIView, It is used to show alert kind of view to highlight some info"}],"topicSections":[{"title":"Files","identifiers":["doc:\/\/com.sample.PopupKit\/documentation\/PopupKit\/Popup","doc:\/\/com.sample.PopupKit\/documentation\/PopupKit\/PopupView"]},{"identifiers":["doc:\/\/com.sample.PopupKit\/documentation\/PopupKit\/PopupKit"],"title":"Classes"}],"kind":"symbol","primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"inlineContent":[{"type":"text","text":"Example Usage:"}],"type":"paragraph"},{"syntax":"swift","code":["import PopupKit","","let popup = Popup(with: \"Popup Title\", ","                  message: \"Popup Message\", ","                  dismissTitle: \"Dismiss Button Title\")","addSubview(popup)",""],"type":"codeListing"},{"syntax":"swiftui","type":"codeListing","code":["import PopupKit","","PopupView(with: \"Popup Title\", ","                  message: \"Popup Message\", ","                  dismissTitle: \"Dismiss Button Title\") {","    \/\/ Do something","}","",""]},{"content":[{"inlineContent":[{"type":"text","text":"Keep "},{"inlineContent":[{"type":"text","text":"Popup Title"}],"type":"strong"},{"type":"text","text":" in one line only."}],"type":"paragraph"}],"name":"Note","style":"note","type":"aside"}]}],"identifier":{"url":"doc:\/\/com.sample.PopupKit\/documentation\/PopupKit","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/popupkit"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/popupkit"]}],"hierarchy":{"paths":[[]]},"references":{"doc://com.sample.PopupKit/documentation/PopupKit":{"type":"topic","title":"PopupKit","kind":"symbol","url":"\/documentation\/popupkit","identifier":"doc:\/\/com.sample.PopupKit\/documentation\/PopupKit","abstract":[{"text":"Popup class conforms to UIView, It is used to show alert kind of view to highlight some info","type":"text"}],"role":"collection"},"doc://com.sample.PopupKit/documentation/PopupKit/PopupKitVersionNumber":{"type":"topic","fragments":[{"kind":"identifier","text":"PopupKitVersionNumber"}],"identifier":"doc:\/\/com.sample.PopupKit\/documentation\/PopupKit\/PopupKitVersionNumber","url":"\/documentation\/popupkit\/popupkitversionnumber","kind":"symbol","title":"PopupKitVersionNumber","role":"symbol","abstract":[{"type":"text","text":"Project version number for PopupKit."}]},"doc://com.sample.PopupKit/documentation/PopupKit/PopupView":{"navigatorTitle":[{"kind":"identifier","text":"PopupView"}],"type":"topic","identifier":"doc:\/\/com.sample.PopupKit\/documentation\/PopupKit\/PopupView","url":"\/documentation\/popupkit\/popupview","role":"symbol","abstract":[{"text":"A SwiftUI view representable for ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.sample.PopupKit\/documentation\/PopupKit\/Popup","type":"reference"},{"text":" class","type":"text"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PopupView"}],"title":"PopupView"},"doc://com.sample.PopupKit/documentation/PopupKit/Popup":{"identifier":"doc:\/\/com.sample.PopupKit\/documentation\/PopupKit\/Popup","role":"symbol","url":"\/documentation\/popupkit\/popup","type":"topic","kind":"symbol","title":"Popup","abstract":[{"text":"Popup View class used to show alert type view","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Popup"}],"navigatorTitle":[{"kind":"identifier","text":"Popup"}]},"doc://com.sample.PopupKit/documentation/PopupKit/PopupKitVersionString":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.sample.PopupKit\/documentation\/PopupKit\/PopupKitVersionString","abstract":[{"text":"Project version string for PopupKit.","type":"text"}],"fragments":[{"text":"PopupKitVersionString","kind":"identifier"}],"type":"topic","title":"PopupKitVersionString","url":"\/documentation\/popupkit\/popupkitversionstring"},"doc://com.sample.PopupKit/documentation/PopupKit/PopupKit":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PopupKit"}],"identifier":"doc:\/\/com.sample.PopupKit\/documentation\/PopupKit\/PopupKit","navigatorTitle":[{"text":"PopupKit","kind":"identifier"}],"url":"\/documentation\/popupkit\/popupkit","abstract":[],"title":"PopupKit","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/topicSections","value":[{"title":"Files","identifiers":["doc:\/\/com.sample.PopupKit\/documentation\/PopupKit\/Popup"]},{"title":"Variables","identifiers":["doc:\/\/com.sample.PopupKit\/documentation\/PopupKit\/PopupKitVersionNumber","doc:\/\/com.sample.PopupKit\/documentation\/PopupKit\/PopupKitVersionString"]}]},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":"Popup","path":"\/references\/doc:~1~1com.sample.PopupKit~1documentation~1PopupKit~1Popup\/title","op":"replace"},{"value":[{"kind":"identifier","text":"Popup"}],"op":"replace","path":"\/references\/doc:~1~1com.sample.PopupKit~1documentation~1PopupKit~1Popup\/fragments"}]}]}